### ISSUE TITLE
Possible misspelling causing errors when not using global clients

### ISSUE THREAD

**Issue by aclemmensen** [silviucpp/erlkaf#1]
`undefied` here:

https://github.com/silviucpp/erlkaf/blob/master/src/erlkaf_app.erl#L20

Appears to always cause the other branch to be run.

**Comment by silviucpp** [comment]
Hello, 

Thanks for reporting. I fixed the problem 

Silviu

**Comment by aclemmensen** [comment]
No problem. Thanks for fixing it. :) I worked around it by actually assigning the value `undefied` in my environment.
