### ISSUE TITLE
segfault when stopping client

### ISSUE THREAD

**Issue by tsloughter** [silviucpp/erlkaf#11]
I haven't been able to reproduce this outside of the test suite of an internal project, so I'm opening in hopes you might have seen this before.

In the test suite I was going to have a consumer start and stop with the suite that needs it. A producer is configured in sys.config and started when the the application is booted during the start of the test suites.

The segfault happens when attempting to stop the consumer during test suite cleanup, `erlkaf:stop_client(client_consumer)`. Logs look like:

```
22:03:18.453 [info] stop consumer for: <<"events">> partition: 0
22:03:18.453 [info] wait for consumer client client_consumer to stop...
22:03:18.529 [info] client client_consumer stopped
Segmentation fault (core dumped)
```

I tried reproducing by manually starting and stopping a consumer but it works fine.

Do you have any theories on possible reasons for a segfault that might help me make this reproducible?

**Comment by silviucpp** [comment]
Hello,
I fixed while ago a similar issue found in our production: 

https://github.com/silviucpp/erlkaf/commit/07bcee6a7e3e8627f55aec49eb69fd0ce0b89962

But till that moment I was not able to find something similar. 

Do you think you can start your erlang app using gdb and provide a backtrace when is crashing ? 
Are you familiar with this or you need full instructions ?

If you need full instructions let me know what OS and erlang version you are using.

Silviu

**Comment by tsloughter** [comment]
Haven't touched gpb in over a decade so definitely would be faster if you don't mind giving instructions :)

Versions:

OTP 20.3

Linux version 4.18.0-16-generic (buildd@lcy01-amd64-022) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)) #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019

**Comment by silviucpp** [comment]
In order to generate core dumps when is crashing you need to have core dumps activated on that machine. You can check using `ulimit -c` and should show:

- unlimited - enable
- 0 - disabled

After the app crashes do :

Run `gdb {path_to_erlang_erts}/bin/beam.smp {coredump_file} -d {erlang_otp_source_path}/erts/emulator` where:

- `{path_to_erlang_erts}` - The full path to the erlang beam.smp that generated the dump
- `{coredump_file}` - Full path to the generated core dump (most of the time generated in /var/crash/)
- `{erlang_otp_source_path}` - The full path to the erlang source code that belongs to the version you are running
Example:

```sh
gdb /usr/local/myapp/erts-8.0.3/bin/beam.smp /var/crash/core_node01_1473846636_20469_beam.smp_11_0 -d /home/silviu.caragea/otp-OTP-19.0.5/erts/emulator
```
Once you see `gdb` prompt, type `backtrace` or `backtrace full` and you will see the stack

Silviu

**Comment by tsloughter** [comment]
Thanks.

The Erlang it is running with doesn't have the source with it. So I downloaded the source of the same version, 20.3.2, and tried using that but I'm getting:

```
warning: Can't read pathname for load map: No error information
```

Which I assume is related to why everything is `?? ()`. 

I'd forgotten about how much was stripped when these images were built. All this stripping during after the build is why it can't get symbols? https://github.com/erlang/docker-erlang-otp/blob/master/20/alpine/Dockerfile#L42-L48

I assume so, so working on getting this able to run on my host machine so I can get the backtrace.

**Comment by tsloughter** [comment]
Damn, not getting anything when running with my local Erlang install either. And the only warning when run this time is `warning: the debug information found in "/lib64/ld-2.28.so" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).`

**Comment by silviucpp** [comment]
Cant you just take the OTP and compile ?

```sh
#!/bin/sh
OTP_RELEASE=21.3
wget https://github.com/erlang/otp/archive/OTP-$OTP_RELEASE.zip
unzip OTP-$OTP_RELEASE.zip
cd otp-OTP-$OTP_RELEASE
./otp_build autoconf
./configure
export MAKEFLAGS=-j8
make
sudo rm -rf /usr/local/lib/erlang
sudo make install
```

**Comment by silviucpp** [comment]
Maybe you can do this on your own machine or in a VM just for testing

**Comment by tsloughter** [comment]
That's how I build on my machine. But yea, I'll try in a bit with a fresh download, build and install to be sure.

**Comment by tsloughter** [comment]
It seems the issue isn't the symbols for Erlang. If I run `thread apply all bt full` in gdb I see dumps that have Erlang related symbols:

```
#4  scheduler_wait (fcalls=fcalls@entry=0x7f3e80c18da4, esdp=esdp@entry=0x7f3e82859580, rq=rq@entry=0x7f3e82c03a40)
    at beam/erl_process.c:3560
        timeout = -1
        res = <optimized out>
        timeout_time = <optimized out>
        do_timeout = <optimized out>
        current_time = <optimized out>
        working = <optimized out>
        ssi = 0x7f3e82c047c0
        spincount = <optimized out>
        aux_work = 0
        thr_prgr_active = 1
        flgs = 13
        __erts_msacc_cache = 0x0
        __erts_msacc_state = 4
```

But the backtrace is still nothing:

```
#0  0x00007f3de9bcde18 in ?? ()
#1  0x00007f3e81b3e7a0 in ?? ()
#2  0x00007f3dd575d4f2 in ?? ()
#3  0x18a9d250534fb000 in ?? ()
#4  0x00007f3e83f00f80 in ?? ()
#5  0x00007f3e81b3e7f0 in ?? ()
#6  0x00007f3e81b3e7a0 in ?? ()
#7  0x00007f3e81b3e7a0 in ?? ()
#8  0x0000000000000000 in ?? ()
```

**Comment by silviucpp** [comment]
Very strange, that's the way we debug on our servers in production/prelive and so far worked perfectly. And similar steps are described also here: https://www.erlang-solutions.com/blog/how-to-analyse-a-beam-core-dump.html

**Comment by silviucpp** [comment]
@tsloughter can you replicate in case you are striping out all sensitive data from that suite test so I can run myself ?

**Comment by tsloughter** [comment]
@silviucpp I will be trying to reproduce this in an example, hopefully I can find time to put that together this week.

**Comment by silviucpp** [comment]
Thanks a lot !

**Comment by silviucpp** [comment]
Give me few days because I found a crash while developing something. After I will publish the fix let's see if it's what you found as well.

**Comment by silviucpp** [comment]
How I can see the logs in console sent with OTP Logger (https://github.com/silviucpp/erlkaf/commit/f453951ea51cf549dd5de92e2bb6599a79a6027e) . I see lager doesn't catch them to display. Idea of using lager was that we are sending all logs in graylog using a lager handler.

Any idea how I can make lager to catch all logs generated using OTP Logger ?

**Comment by tsloughter** [comment]
@silviucpp crap, I didn't realize that actually isn't supported yet. I asked Vagabond about it in the lager freenode channel. I guess you'll want to just revert my change for now and go back to requiring lager.

**Comment by silviucpp** [comment]
@tsloughter please check https://github.com/silviucpp/erlkaf/tree/consumer-fix and see if fix the problem for you.

I still didn't finished all my tests but I'm wonder if fixes your problem.

I will revert that OTP lager for the moment.

**Comment by silviucpp** [comment]
@tsloughter I performed lot of tests scenarios on this consumer-fix branch and also looked with profilers for finding memory leaks (found 2 actually generated when re-balance occurs). Everything seems behaving properly now. Can you please test ?

Actually to simulate the crash on the master branch is simple:

In the init consumer handler just throw and exception:

```erl
init(Topic, Partition, Offset, Args) ->
    io:format("### consumer -> init topic: ~p partition: ~p offset: ~p args: ~p ~n", [Topic, Partition, Offset, Args]),
    throw(crash_me),
    {ok, #{}}.
```
Let me know if problem is fixed for you now 

Silviu

**Comment by tsloughter** [comment]
@silviucpp yup, it works!

**Comment by silviucpp** [comment]
Great . Will make a release soon

Silviu

**Comment by silviucpp** [comment]
Fixed in master. will release the version today
