### ISSUE TITLE
Flush producer during shutdown

### ISSUE THREAD

**Issue by tsloughter** [silviucpp/erlkaf#12]
There isn't a `erlkaf:flush` function so I'm wondering if rdkafka or erlkaf internally has some logic to flush during shutdown of the node?

**Comment by silviucpp** [comment]
When produce is closed messages are flushed while erlkaf is calling:

```
rd_kafka_consumer_close(consumer->kf);
```

**Comment by silviucpp** [comment]
Only note I have is that in case kafka is down when you close the producer, the messages are lost. 
I'm planning to put them in the local queue but unfortunately is not yet supported in librdkafka.

in erlkaf_producer.erl you will find this comment
```erl
%todo:
% * we need support in case we shutdown the producer to get back the pending messages from librdkafka and
%   write them in the local queue. this is not supported now by librdkafka
%   more details: https://github.com/edenhill/librdkafka/issues/990 
```

**Comment by silviucpp** [comment]
Hello @tsloughter ,

In case everything it's clear please close this. In case you have pending questions let me know

Silviu

**Comment by tsloughter** [comment]
Ok, great. And regular application stop will cause it to close the producer gracefully like this? Just want to make sure if I should be safe and have some cleanup code in our application's `stop` that goes through all clients and closes them.

**Comment by silviucpp** [comment]
yes. erlkaf:stop() will gracefully shutdown the consumers and producers.

**Comment by tsloughter** [comment]
Great, thanks!
