### ISSUE TITLE
Hex package 1.1.7 failure undef erl_nif:set_log_process

### ISSUE THREAD

**Issue by tsloughter** [silviucpp/erlkaf#16]
When using the hex package, version 1.1.7, it fails during `init` of `erlkaf_logger` because of `undef erl_nif:set_log_process`.

I look at the code for the module in the package and it seems fine.

When using the master branch as the dep in rebar3 it works fine, so seems to either be a problem with the package itself or just needs a new version published off current master.

**Comment by silviucpp** [comment]
Very strange.. there is no change between 1.1.6 and 1.1.7 in this are or between master..

**Comment by silviucpp** [comment]
Anyway I pushed a new version from master. Can you check ?

Silviu

**Comment by silviucpp** [comment]
@tsloughter  any feedback ?

**Comment by tsloughter** [comment]
Hey, sorry about that, I was out some of last week and today is a day off as well so I haven't tried this yet at work. I'll do so tomorrow and let you know. Thanks

**Comment by tsloughter** [comment]
This is really weird... with 1.1.8 I'm getting:

```
===> Dependency failure: source for erlkaf does not contain a recognizable project and can not be built
```

I checked in the tarball and it look fine...

**Comment by silviucpp** [comment]
I have no idea what changed.. other than updating my rebar3 ...

**Comment by tsloughter** [comment]
@silviucpp I see the issue. The package has no `src/erlkaf.app.src` file somehow.

**Comment by tsloughter** [comment]
What rebar3_hex version are you using? Could have been a bug in there.

**Comment by silviucpp** [comment]
Good catch! 

Check 1.1.9 I added the  "src/*.src" files. Was never there but probably the old rebar3 I used automatically included this file without being into the files list. 

Now it's ok ?

**Comment by silviucpp** [comment]
@tsloughter  please confirm that problem was fixed so I can close this issue.

Thanks
Silviu

**Comment by tsloughter** [comment]
Oops, sorry, yes, it works. Thanks!
