### ISSUE TITLE
Error compiling on elixir 1.13.1

### ISSUE THREAD

**Issue by escobera** [silviucpp/erlkaf#42]
I'm getting an error the first time I try to build the nif using the latest version of elixir. 

Last log lines are as follows
```
~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/deps ~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf
~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf
make[1]: Entering directory '/root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/c_src'
 CPP    erlkaf_consumer.cc
 CPP    queuemanager.cc
 CPP    topicmanager.cc
 CPP    erlkaf_nif.cc
 CPP    queuecallbacksdispatcher.cc
 CPP    erlkaf_logger.cc
 CPP    nif_utils.cc
 CPP    erlkaf_message.cc
 CPP    erlkaf_producer.cc
 CPP    erlkaf_config.cc
 LD     erlkaf_nif.so
make[1]: Leaving directory '/root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/c_src'
===> Analyzing applications...
===> Compiling erlkaf
===> Missing artifact priv/erlkaf_nif.so
** (Mix.Error) Could not compile dependency :erlkaf, "/root/.mix/rebar3 bare compile --paths /root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You may run Mix.install/2 to try again or change the arguments to Mix.install/2 to try another version
```

**Steps to reproduce**

> I created a simplified flow using docker, but it is happening on my local installation as well.

 
Using the following `Dockerfile` to get latest elixir version and erlkaf build dependencies

```Dockerfile
FROM elixir:1.13.1-slim AS app_builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends git build-essential libssl-dev libcrypto++-dev zlib1g-dev libsasl2-dev \
                     liblz4-dev libzstd-dev ca-certificates
```

Then just build, start the container and test the installation:

```shell
docker build -t erlkaf_test .
docker run -it --rm erlkaf_test

iex(1)> Mix.install([{:erlkaf, github: "silviucpp/erlkaf"}])

# there will be a propmt to install rebar
```

Then the error occurs, after that if you try again on the same image it installs just fine. Maybe it is related to https://github.com/elixir-lang/elixir/issues/11530

**Comment by silviucpp** [comment]
Hello @escobera , 

I have no experience with elixir unfortunately. looking to the error (`===> Missing artifact priv/erlkaf_nif.so`) for some reason the erlkaf_nif.so is not in the priv folder ?

**Comment by silviucpp** [comment]
Maybe @tsloughter can help here. I know he did few fixes for elixir on the project.

**Comment by tsloughter** [comment]
Sounds like an issue that was found recently with the `pc` plugin that got patched and I made a release 1.14.0 https://hex.pm/packages/pc/1.14.0

**Comment by escobera** [comment]
Thanks @silviucpp and @tsloughter for the quick reply!

I don't see any explicit mention of the `pc` plugin in https://github.com/silviucpp/erlkaf/blob/master/rebar.config, how do I force this new version on my environment?

**Comment by tsloughter** [comment]
Oh damn, my bad, erlkaf uses `make` instead of the `pc` plugin. The Makefile needs to be patched to write to `$REBAR_BARE_COMPILER_OUTPUT_DIR/priv` instead of `./priv` -- I guess it'll need to check if that env var exists since if its empty it'd end up being `/priv`. Or maybe `$REBAR_BARE_COMPILER_OUTPUT_DIR/./priv` would work.

**Comment by silviucpp** [comment]
@tsloughter `$REBAR_BARE_COMPILER_OUTPUT_DIR` is available starting with what rebar3 version ? btw I shoud be able to replicate this in erlang as well right ?

**Comment by silviucpp** [comment]
@escobera thanks for the patch ! I will merge this once all the travis builds pass
