### ISSUE TITLE
Hex.pm missing documentation

### ISSUE THREAD

**Issue by VitorTrin** [silviucpp/erlkaf#46]
the[ link in the hex.pm page to the documentation](https://hexdocs.pm/erlkaf/) 404's

**Comment by silviucpp** [comment]
This is because there is no documentation in hex. Use the githut readme file in order to see how to use the project.

**Comment by VitorTrin** [comment]
Is the link generated automatically? It cannot be removed to avoid confusion?

**Comment by silviucpp** [comment]
Yes it is automatically generated. I have no clue if it's something we can do to disable it.
