### ISSUE TITLE
Seek to offset

### ISSUE THREAD

**Issue by jessiahr** [silviucpp/erlkaf#5]
I am looking at using this for something I am working on and I was wondering if there is a way to seek to an offset in a consumer or if it must start from the beginning / current time?

**Comment by oawoyemi** [comment]
Is there a schedule for upgrading to librdkafka 0.11.5 to support this and other features such as configurable partitioners- murmur2 hashing etc?

**Comment by silviucpp** [comment]
I'll probably do it soon

**Comment by silviucpp** [comment]
@oawoyemi project was migrated to librdkafka 0.11.5 and the available options can be achieved via the `partitioner` config.

**Comment by silviucpp** [comment]
I looked over the seek offset and seems it's available only when you manually assign topic and partitions to consume from. 

erlkaf it's using the subscribe api which subscribe to one or more topics and the distributed balanced consumer group functionality will assign a subset(0..N) of those partitions to the consumer based on the assignment strategy.

Integrating the assign api which allows to manually assign some partitions is not into my plans.
