### ISSUE TITLE
Produce tombstones

### ISSUE THREAD

**Issue by macasado86** [silviucpp/erlkaf#51]
Hi,

I'm unable to produce tombstones (null messages) to kafka for a specified key in a compacted topic. I think the problem is that the producer is always expecting a value with a binary content and when an undefined atom arrives, the `make_badarg` method is invoked.

I would like to know if this is not supported or I'm missing something.

Thank you

**Comment by silviucpp** [comment]
You are right is not supported . It's very easy to add this. I will make a fix in the next days.

**Comment by silviucpp** [comment]
Please test on last master. The tombstones should be sent as `undefined`.

**Comment by macasado86** [comment]
It works perfectly

Thank you very much!

**Comment by silviucpp** [comment]
You are welcome
