### ISSUE TITLE
headers support

### ISSUE THREAD

**Issue by tsloughter** [silviucpp/erlkaf#6]
It looks like headers aren't exposed but are supported by the current version of librdkafka, correct?

I can take a wack at it if it is simply adding a field to the message record and setting it on decode and using it when calling librdkafka's produce function?

**Comment by jhchabran** [comment]
> It looks like headers aren't exposed but are supported by the current version of librdkafka, correct?

Not the maintainer but fellow erlkaf user, but yeah librdkafka doc on the commit that erlkaf uses has the headers support https://github.com/edenhill/librdkafka/blob/44242a464c43e09c685f47a7f3dca2963b10e2a9/src/rdkafka.h#L904 

I'd be interested in the patch if you go for it 😄

**Comment by tsloughter** [comment]
Cool, guess I will after I get a project moved over to this from kinesis. So shouldn't be too long before I start hacking on this.

**Comment by silviucpp** [comment]
Hello Tristan,

Any pull request is welcome. I don't have too much time now to implement this even if doesn't seems something complex.

Silviu

**Comment by tsloughter** [comment]
Finally looking at this again and maybe not as clear cut as I'd hoped.

To send headers it has to use `rd_kafka_producev` which takes a first argument that `rd_kafka_produce` does not, see the example here https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c#L620

Looking through `erlkaf_producer` it looks like an `rk` of the same type is used to create a TopicManager in `enif_producer_new`.

Should I be pulling `rk` from the producer somehow, similar to what it does with topic, `rd_kafka_topic_t* topic = producer->topics->GetOrCreateTopic(topic_name);`?

**Comment by silviucpp** [comment]
you can take it very simple because it's part of enif_producer struct.

just do:

rd_kafka_producev(producer->kf

**Comment by silviucpp** [comment]
I'll commit something this week with headers support :)) I need this into a project

**Comment by tsloughter** [comment]
hah, ok, cool, I was so close too :). I'm creating the headers and passing to producev but when I check a message for headers in the consumer with `rd_kafka_message_headers` I get the error enoent meaning no headers on the message.

**Comment by silviucpp** [comment]
Please check the "headers_support" branch.

Headers are supported as `proplists` or `maps`. (even if kafka allows multiple headers with same name).
Internally kafka supports the keys and values only as binaries. `erlkaf` will convert them automatically to binary in case you provide numbers, atoms,etc.

in test folder you can find a small example (starts a consumer and a producer and whatever you produce will be consumed and displayed in logs):

```
test_consume_produce:create(<<"172.17.3.163:9092">>).

% with headers as proplists (no binary for values)
test_consume_produce:produce(<<"key1">>, <<"value1">>, [{<<"hk1">>, 1}, {<<"hk1">>, 2}]).

% no headers
test_consume_produce:produce(<<"key1">>, <<"value1">>).

% with headers as map
test_consume_produce:produce(<<"key1">>, <<"value1">>, #{k => v}).
```

**Comment by silviucpp** [comment]
For me works fine, let me know if you find something. In case headers are not used same librdkafka api will be called as before. In case headers are used the new `rd_kafka_producev` will be used.

**Comment by tsloughter** [comment]
@silviucpp great!

I was again not getting headers in the consumer, which lead me to realize the `spotify/kafka` image I'm running to tests against is 0.10 and I guess headers were added in 0.11 :), so that explains a lot.

Thanks! One suggestion I have is to move `rebar3_hex` to a `project_plugin`. Project plugins are only built when you are building the project directly, as in not as a dependency. Since `rebar3_hex` isn't needed when `erlkaf` is a dependency this is nice to users.

```
{project_plugins, [rebar3_hex]}.
```

In order to use the test modules I also added `{profiles, [{test, [{deps, [brod]}]}]}.` locally so I didn't have to remove the brod header including. But that is less important as it doesn't effect users of the dependency.

**Comment by silviucpp** [comment]
Hello,

I moved to {project_plugins, [rebar3_hex]}. 

Regarding tests yes there is work to be done here. to have some nice tests that are testing the library. 
The scripts from there are only used by me to load test and play with the lib.

**Comment by silviucpp** [comment]
I'll close this issue as time I merged the support in master and released a new version.

If you have any other suggestions or contributions fee free to open bugs/pull requests.
