### ISSUE TITLE
Any plans to make a new release?

### ISSUE THREAD

**Issue by dmccown** [silviucpp/erlkaf#72]
Do you have any plans to make a new release? Could I help by starting a PR? We're currently pinned to a SHA on master. I'd love to get to a release artifact.

Thanks!

**Comment by silviucpp** [comment]
I will soon. waiting fro travis to reload my account with open source credits so I can test the builds. 

Silviu

**Comment by silviucpp** [comment]
Release completed

**Comment by dmccown** [comment]
Thank you!On Apr 23, 2024, at 11:03 PM, Silviu Caragea ***@***.***> wrote:﻿
Release completed
