### ISSUE TITLE
Kafka producer throwing warnings on default configuration

### ISSUE THREAD

**Issue by stanczyk280** [silviucpp/erlkaf#73]
These 4 default configurations are injected when not specified by `apply_kafka_default_config/1` routine from `erlkaf_config.cc`.

```
bool appy_kafka_default_config(rd_kafka_conf_t* config)
{
    if(rd_kafka_conf_set(config, "enable.auto.commit", "true", NULL, 0) != RD_KAFKA_CONF_OK)
        return false;

    if(rd_kafka_conf_set(config, "enable.auto.offset.store", "false", NULL, 0) != RD_KAFKA_CONF_OK)
        return false;

    if(rd_kafka_conf_set(config, "enable.partition.eof", "false", NULL, 0) != RD_KAFKA_CONF_OK)
        return false;

    if(rd_kafka_conf_set(config, "allow.auto.create.topics", "true", NULL, 0) != RD_KAFKA_CONF_OK)
        return false;
...
```

It produces warnings everytime it starts:

`CONFWARN [thrd:app]: Configuration property enable.auto.commit is a consumer property and will be ignored by this producer instance`
`CONFWARN [thrd:app]: Configuration property enable.auto.offset.store is a consumer property and will be ignored by this producer instance`
`CONFWARN [thrd:app]: Configuration property enable.partition.eof is a consumer property and will be ignored by this producer instance`
`CONFWARN [thrd:app]: Configuration property allow.auto.create.topics is a consumer property and will be ignored by this producer instance`

**Comment by silviucpp** [comment]
You are right. but this doesn't affect the functionality in any way. I need to change the code to put a flag if the the object is consumer or producer and to apply them only on producer. Any PR is welcome
