### ISSUE TITLE
Logger throwing exception

### ISSUE THREAD

**Issue by sueng66** [silviucpp/erlkaf#75]
I don't have this problem when I setup on my Debian 12 but got this error on RHEL 8 :

`=CRASH REPORT==== 5-Sep-2024::14:26:43.430336 ===
  crasher:
    initial call: erlkaf_logger:init/1
    pid: <0.260.0>
    registered_name: []
    exception error: no function clause matching 
                     logger:do_log_allowed(warning, 
                                           {<<"rdkafka#producer-1 CONFWARN [thrd:app]: Configuration property enable.auto.commit is a consumer property and will be ignored by this producer instance">>,
                                            []},
                                           #{file =>
                                                 "/home/admin.pnbp/hyperx/hyperx_iso8583/_build/default/lib/erlkaf/src/erlkaf_logger.erl",
                                             gl => <0.257.0>,line => 42,
                                             mfa =>
                                                 {erlkaf_logger,log_message,4},
                                             pid => <0.260.0>,
                                             time => 1725521203430245},
                                           #Ref<0.2150491889.2871656455.130737>) (logger.erl, line 1087)
      in function  erlkaf_logger:loop/0 (/home/admin.pnbp/hyperx/hyperx_iso8583/_build/default/lib/erlkaf/src/erlkaf_logger.erl, line 30)
    ancestors: [erlkaf_sup,<0.258.0>]
    message_queue_len: 3
    messages: [{log_message,4,<<"rdkafka#producer-1">>,<<"CONFWARN">>,
                               <<"[thrd:app]: Configuration property enable.auto.offset.store is a consumer property and will be ignored by this producer instance">>},
                  {log_message,4,<<"rdkafka#producer-1">>,<<"CONFWARN">>,
                               <<"[thrd:app]: Configuration property enable.partition.eof is a consumer property and will be ignored by this producer instance">>},
                  {log_message,4,<<"rdkafka#producer-1">>,<<"CONFWARN">>,
                               <<"[thrd:app]: Configuration property allow.auto.create.topics is a consumer property and will be ignored by this producer instance">>}]
    links: [<0.259.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27 
    reductions: 281
  neighbours:
`
What's the problem ?

**Comment by sueng66** [comment]
The erlang form EPEL repo is OTP 22 quite old, the problem is resolve when I am using OTP 26

**Comment by silviucpp** [comment]
Honestly I don't support such old OTP versions. If you have this problem on OTP 24 + let me know. Even 24 I think is exaggerated.
